### ISSUE TITLE
Reply and click notification

### ISSUE THREAD

**Issue by magnusja** [Neo11/ChitChat#1]
Hey,

the JS function openChat() won't click the chat anymore. This results in answering the wrong chat when replying via notification. I have the same problem in my project WhatsQt, but no idea how to solve it. I think it is a ReactJS related bug/behaviour that jQuery's click function does not work anymore.

Any idea how to make this work again?

Thanks in advance & kind regards.

**Comment by Neo11** [comment]
Hi, i have no idea why the click() doesn't work anymore.
Maybe a direct call of the function called after a click will help. But while debugging with chrome I can't find a matching ActionListener on the DOM-Elements...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
I think i found the solution for this ... doing last tests ... will upload code if everything works :)

**Comment by magnusja** [comment]
Nice, works for me, thanks!

**Comment by c-o-m-m-a-n-d-e-r** [comment]
welcome
