### ISSUE TITLE
Back arrow issue

### ISSUE THREAD

**Issue by stasky15** [Neo11/ChitChat#17]
The "back" arrow at "3 vertical dots menu" -> Profile & status cover the red, yellow and green button (at least on Mac).I can't go back from this menu. I need to force the exit.

![captura de pantalla 2016-03-10 20 22 27](https://cloud.githubusercontent.com/assets/12661382/13681633/70b2c1f8-e6fe-11e5-87b8-d17d25e87f5f.png)

BTW, thanks for resurrecting this application as original ChitChat fork.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
you can go back but its tricky hehe...
this bug i'm already fixing.

thanks for that ticket

**Comment by c-o-m-m-a-n-d-e-r** [comment]
It's fixed ... would be in the next release!
