### ISSUE TITLE
Forwarding messages from one contact to another does not work

### ISSUE THREAD

**Issue by abedzantout** [Neo11/ChitChat#22]
the popup where you pick which contact you want to forward a message to basically flickers and nothing happens.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
mhhh can't confirm ... here is everything working ... 
Is it possible to make a Screenshot?

**Comment by abedzantout** [comment]
@c-o-m-m-a-n-d-e-r I'll see what I can do, taking a screenshot is impossible due to how fast it happens. You can forward a message(regardless if it is text, image, etc..) from one contact to another without problem?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes ... without any problems ...

It sounds like a local Problem !?

**Comment by abedzantout** [comment]
@c-o-m-m-a-n-d-e-r I believe not, I did a clean installation and the problem persist. I am using OS X Al Capitan 10.11.3.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
ok... i'm too on this Version ... can you check without the wrapper?

https://web.whatsapp.com

**Comment by VagishVela** [comment]
I also found this issue when I tested it. It lets me go through to forward and select the user then it flickers and does nothing. I compared against the web.whatsapp.com. On web.whatsapp.com it asks me "Forward message to xxx?" but on the app it doesn't.

**Comment by VagishVela** [comment]
I found the issue, it was skipping the "Forward message to xxx?" box. I've fixed it and submitted a pull request. #23

**Comment by c-o-m-m-a-n-d-e-r** [comment]
ahhh now i understand ... yes... thanks for the commit will test it ... :-)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Tested and looks good ... Thx @VagishVela ... have merged it into master ... will be available with next release!

**Comment by abedzantout** [comment]
@c-o-m-m-a-n-d-e-r @VagishVela Great job guys. thank you looks good

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes but we have to fix start new chat too... found it out yesterday that there is the same problem

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r I think new chat has a different issue. The drawer only shows partially on mine.
@c-o-m-m-a-n-d-e-r @abedzantout I've created issue #27 for this.
