### ISSUE TITLE
Developing for ChitChat...

### ISSUE THREAD

**Issue by VagishVela** [Neo11/ChitChat#24]
How do I test my changes? It says:
No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “85EU5W2C4T” were found.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Change it in the project Settings ...

ChiChat - General

**Comment by VagishVela** [comment]
Thanks, I'm getting used to working with xCode. I didn't know if I had to change the settings, or had to make it work that way (with those settings).

**Comment by c-o-m-m-a-n-d-e-r** [comment]
no you can change how you need it ... :-)
