### ISSUE TITLE
Application loses focus on new message arrival

### ISSUE THREAD

**Issue by abedzantout** [Neo11/ChitChat#30]
while a chat is open and you receive a message from another contact, the whole application window will lose focus (but does not crash). The user is forced to click on the application window again to regain focus and continue typing normally.

**Comment by VagishVela** [comment]
@abedzantout I've been testing this out on ChitChat 1.5, 2.2 and the latest code on ChitChat develop branch and I can't reproduce this. Can you let me know what your steps were? And does this happen on ChitChat 2.2? You can download it [here](https://github.com/Neo11/ChitChat/releases).

**Comment by abedzantout** [comment]
@VagishVela yes it does happen on ChitChat 2.2. No need to reproduce anything. Just open the latest ChitChat (2.2), and enter a conversation. While typing in the textfield there, if you receive a message from another contact , the application loses focus.

**Comment by Neo11** [comment]
I have the same problem, but only while I am writing in the moment I get the notifikation.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
will check this... i have an idea what it is...

**Comment by VagishVela** [comment]
@abedzantout I never had any issues while typing. But I didn't try typing at the exact moment that a message was recieved. Also I haven't gotten the losing focus thing with the whole application.

Does this happen on WhatsApp web as well?

**Comment by abedzantout** [comment]
@VagishVela this usually happens at the exact moment you receive a notification. I haven't tested it on WhatsApp web but I doubt the problem exists there. I'll check and let you know later today.

**Comment by VagishVela** [comment]
@abedzantout Is this still happening?
