### ISSUE TITLE
Contact sidebar too small

### ISSUE THREAD

**Issue by dschuessler** [Neo11/ChitChat#34]
When clicking on "New contact", the sidebar coming from the left is too small.

![bildschirmfoto 2016-03-29 um 21 11 36](https://cloud.githubusercontent.com/assets/5774545/14120420/078c5a46-f5f3-11e5-82cc-57b54e833dd0.png)

This is also present in 1.5.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
can't confirm this ... also after the today whatsapp update!

just checked ... what osx / safari version you are using?

**Comment by VagishVela** [comment]
This has been fixed. We just need a new release, I fixed it along with the new message bug.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
ok ... great ! :-)
