### ISSUE TITLE
Contact Selector Screen is cut off

### ISSUE THREAD

**Issue by antonbkn** [Neo11/ChitChat#37]
Hee guys, sweet that the development of ChitChat is continued here. Just a small bug. When clicking on the _New Chat_ button, the contact selector is now fully shown. See the screenshot attached. 

![schermafbeelding 2016-04-06 om 16 22 25](https://cloud.githubusercontent.com/assets/16103022/14320144/3d7984d6-fc14-11e5-92d8-cb7b7e420650.png)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
its fixed:

https://github.com/Neo11/ChitChat/issues/34

**Comment by antonbkn** [comment]
Ah I overlooked this. However, I do have the latest version (2.2). Ill download and install again, maybe this makes a difference. 

**Edit:**
I have tried again, still same error..

**Comment by c-o-m-m-a-n-d-e-r** [comment]
it isn't released yet sry ...

neo have to make new build but he is busy wirh studying

**Comment by antonbkn** [comment]
Ah ok, no problem. Ill wait for the fix thx

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r Is @Neo11 the only one who can release it?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
not really sure, but we shouldn't do this all...

neo has to decide !
