### ISSUE TITLE
Badge in the dock not working

### ISSUE THREAD

**Issue by ghost** [Neo11/ChitChat#40]
Since three day there is no red badge in the dock with the count of the unread messages.

**Comment by ilker55** [comment]
+1 I noticed it too.

**Comment by tomatoTom** [comment]
Any idea how to fix this bug?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i will take a look ...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i think i got it ... display the badge is working again!
doing some tests now

**Comment by c-o-m-m-a-n-d-e-r** [comment]
working for me ... is checked into master..

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Done
