### ISSUE TITLE
detailed contact or group information is broken

### ISSUE THREAD

**Issue by tomatoTom** [Neo11/ChitChat#42]
The contact or group information can't be displayed. A empty screen appears. But in WhatsApp Web it works fine. Can you fix this? 

Best Regards,

Tom

**Comment by tomatoTom** [comment]
When will the app be updated?
The error is in the inject.js file...
somewhere here:
`var styleAdditions = document.createElement('style');
styleAdditions.textContent = 'div.pane-list-user { opacity:0; } \
div.pane-list-user > div.avatar { width: 0px; height: 0px; } \
div.app-wrapper::before { opacity: 0; } \
div.drawer-title { left:60px; bottom:17px; } \
div.chat.media-chat > div.chat-avatar { opacity: 0;} \
div.app.three, div.app.two { top: 0px; width: 100%; height: 100%; } \
.drawer-container-left { width: 100%; } \
@media screen and (max-width:1024px) { \
.pane-list { width: 100%; } \
.drawer-container-mid, .drawer-container-right, .pane-chat, .pane-intro, .pane-info, .drawer-container-panel { width: 62%; } \
} \
@media screen and (min-width:1024px) and (max-width:1199px) { \
.pane-list, .pane-info, .drawer-container-panel { width: 30%; } \
.drawer-container-mid, .drawer-container-right, .pane-chat, .pane-intro { width: 70%; } \
.three .drawer-container-mid, .three .drawer-container-right, .three .pane-chat, .three .pane-intro { width: 40%; } \
} \
@media screen and (min-width:1200px) { \
.pane-list, .pane-info, .drawer-container-panel { width: 359px; } \
.drawer-container-mid, .drawer-container-right, .pane-chat, .pane-intro { width: calc(100% - 359px); } \
.three .drawer-container-mid, .three .drawer-container-right, .three .pane-chat, .three .pane-intro { width: calc(100% - 718px); } \
}\
@media screen and (min-width:1320px) {\
.pane-list, .pane-info, .drawer-container-panel { width: 388px; } \
.drawer-container-mid, .drawer-container-right, .pane-chat, .pane-intro { width: calc(100% - 388px); } \
.three .drawer-container-mid, .three .drawer-container-right, .three .pane-chat, .three .pane-intro { width: calc(100% - 718px); } \
}\
.image-thumb-lores { -webkit-transform: translate3d(0,0,0); } \
.avatar-image { -webkit-transform: translate3d(0,0,0); } \
.drawer-header-small { background-color: #00bfa5; color: #fff; height: 108px; -webkit-box-orient: vertical; -webkit-box-direction: normal; -webkit-flex-direction: column; -ms-flex-direction: column; flex-direction: column; -webkit-box-pack: end; -webkit-justify-content: flex-end; -ms-flex-pack: end; justify-content: flex-end; padding: 0 20px 12px; -webkit-box-align: inherit; -webkit-align-items: inherit; -ms-flex-align: inherit; align-items: inherit; } \
.drawer-header-small .drawer-title { -webkit-box-flex: 0; -webkit-flex: none; -ms-flex: none; flex: none; }\
';
document.documentElement.appendChild(styleAdditions);`

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i will take a look at this

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Fixed with last commit https://github.com/Neo11/ChitChat/commit/951823f0e40d2e48286b3f5c2060332ddbeb9b6d

**Comment by c-o-m-m-a-n-d-e-r** [comment]
fixed too much hahaha ... will recheck

**Comment by c-o-m-m-a-n-d-e-r** [comment]
done
