### ISSUE TITLE
Continuing development for ChitChat?

### ISSUE THREAD

**Issue by VagishVela** [Neo11/ChitChat#43]
I've noticed that this repo and https://github.com/stonesam92/ChitChat aren't being updated anymore.

Did people want this app to have continued development? I also have a issue for this on stonesam92/ChitChat/issues/149

**Comment by maciboy** [comment]
Yes, I’d really like to see some progress and a continued development here in the future :)
ChitChat has some advantages over other tools!
Eg it’s based on Safari. This is a huge benefit, at least for me, since I’m using a 2010 MBP and struggling with a integrated Nvidia graphics. Chrome and apps based on it always trigger this graphic. ChitChat runs seamlessly on the integrated graphics!

WhatsApp’s own client unfortunately is also Chrome-based…

Thanks to all participants here, also in advance ;)

**Comment by VagishVela** [comment]
@maciboy I only recently realized how much of a battery hog that chrome is, so I can see the benefits for those out and about to save battery.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
I'm still here ... but having not so much time at the moment ... and the most things are working for me ...

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r Didn't know you were still working on this, it seemed to have gone quiet a couple of months ago. But thought it might be time to revive this baby!

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r Are you able to do the releases or does @Neo11 have to do them?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i think @Neo11 have to add me to the Developer Team so i can compile release!

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r On ChitChat? Also why are we not pushing this to the AppStore, are we not allowed to? Or is it that we never tried? It might get a more streamlined adoption for this app.

**Comment by Neo11** [comment]
I have no time to spend on the issues. But i can build new releases, if someone else fixes the issues.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Hey @Neo11 , my Mailclient couldn't deliver mail to you ...
Could you please make a release? Fixed some things...

And could you add me into your dev account as team member for chitchat so ich can make releases too? (then i can compile under your team id)

**Comment by VagishVela** [comment]
@Neo11 @c-o-m-m-a-n-d-e-r Awesome!

**Comment by Neo11** [comment]
New Release already here: https://github.com/Neo11/ChitChat/releases/tag/v2.4
Only need to update appcast

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Super! Thanks

**Comment by Neo11** [comment]
@c-o-m-m-a-n-d-e-r Don't know if this is possible. Have no payed Developer Account. So don't know where to add people...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
@Neo11 ah ok ... so i can just compile a release myself .. good to know 👍

**Comment by c-o-m-m-a-n-d-e-r** [comment]
All working now ... so cloesd
