### ISSUE TITLE
ChitChat to AppStore

### ISSUE THREAD

**Issue by VagishVela** [Neo11/ChitChat#45]
I started asking the question in #43
But it seems more appropriate to be a separate issue. Is there a reason we can't have this on the AppStore, enabling more people to find and use this?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i think there are some private api calls used .. so this will be rejected.
i personally don't need it at the app store, so we can use this api calls ...

**Comment by VagishVela** [comment]
@c-o-m-m-a-n-d-e-r I think people normally find [stonesam92/ChitChat](/stonesam92/ChitChat) and see the lack of development and create issues there. We have fixed quite a bit of them here but they aren't getting noticed, which results in people thinking ChitChat is dead while it isn't.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
@VagishVela i don't see any advantage in this for dropping such functions only for publicity!
I believe everybody how comes to github to get ChitChat is able to look at the forks if he saw that stonesam92 isn't anymore supported
