### ISSUE TITLE
Remove the forked from, since the stonesam92 one isn't supported?

### ISSUE THREAD

**Issue by VagishVela** [Neo11/ChitChat#5]
It seems like that version is no longer supported, with the forked version it won't show up if we search for ChitChat in github search.

**Comment by Neo11** [comment]
I think I must make a new repo for this. Maybe I will do this soon.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i believe you can contact github support staff to do that ...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
I think this is solved ...
