### ISSUE TITLE
Rename everything to ChitChat since WhatsMac is long gone

### ISSUE THREAD

**Issue by VagishVela** [Neo11/ChitChat#57]
We probably should make things conform a bit more so we should rename everything.

**Comment by rahul-kumi** [comment]
i will work on the issue.

**Comment by rahulcode22** [comment]
What to rename @VagishVela

**Comment by c-o-m-m-a-n-d-e-r** [comment]
can you explain what you mean?

**Comment by VagishVela** [comment]
There is at least one place I can see which is a folder called WhatsMac. There maybe other places we have which use WhatsMac. Basically renaming them and making sure nothing breaks and if it does fixing the paths to ensure everything works.

A search ( https://github.com/Neo11/ChitChat/search?utf8=%E2%9C%93&q=WhatsMac ) reveals a couple of places we can update it. We can leave the README.md but updating some of these would require more testing and ensure it doesn't break things.

**Comment by VagishVela** [comment]
Looks good and working!
