### ISSUE TITLE
New Version not found

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [Neo11/ChitChat#7]
Hey,
thanks for the Release ... but the Update isn't found.
I already updatet the XML with new Release Notes ... but if i check (from 2.0.1) nothing is found.

Do you signed it with DSA ?

Best

P.S : am i right, you are german? (do you have a direct contact email for me? )

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Damn ... i'm an idiot ;-) found it myself ...

**Comment by Neo11** [comment]
You can use schmidt@kaipho.de
